### ISSUE TITLE
Implements hook_library_info()

### ISSUE THREAD

**Issue by opi** [backdrop-contrib/jstorage#2]
... so that other modules could use `backdrop_add_library('jstorage', 'jstorage')`.

Documentation:
- https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_library_info/1
- https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_add_library/1

**Comment by laryn** [comment]
Thanks, @opi! I didn't know about this -- I thought this type of functionality was all related to the libraries module! I will look into it.

**Comment by opi** [comment]
don't really know about the library module, but it implements [`hook_libraries_info`](https://github.com/backdrop-contrib/libraries/blob/1.x-2.x/libraries.api.php#L203).
Not really sure, but it seems a little bit duplicated to me. Maybe we should as so long term Backdrop dev or module porter @Graham-72

**Comment by laryn** [comment]
@opi Does that commit look right to you? (It seems to be working in my testing.)

**Comment by opi** [comment]
seems good. I haven't tested it though. Add minor comments on https://github.com/backdrop-contrib/jstorage/commit/01657f0cf396f3a5bf142274d63030f4d0e77bf7

**Comment by laryn** [comment]
Thanks again, @opi.
